version: "2"
services:
    web:
        build: .
        image: prestogram/v1 
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
    mysql:
        image: mysql
        env_file: .env
        volumes:
            - ./mysql:/var/lib/mysql